server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: HistoryService

  r2dbc:
    url: ${SPRING_R2DBC_URL:jdbc:h2:mem:historyservicedb}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: ${SPRING_LIQUIBASE_URL:jdbc:h2:mem:historyservicedb}
    user: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    enabled: true

#  jpa:
#    open-in-view: false
#    generate-ddl: false
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        format_sql: true
#    show-sql: true


#logging:
#  level:
#    ROOT: ERROR